### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by schealex** [DeadAirRT/deadairfactionmindatar#1]
Hi there,

first of all let me say thank you for providing your mods and putting in the work. They really enhance the game a lot. I'm also a EVE player so i'm enjoying the fact that you combine those two words.

I'm currently trying to start a new game with all your mods enabled but when i try the amar start with headquarter i'm getting like ~30 fps and even lower ~15 with the map open. I just wanted to know if that is normal with all the map additions and the increased traffic of ships or do i have a problem on my side?

Here are the mods i'm using for that playthrough:

![image](https://user-images.githubusercontent.com/3441348/181934908-502b7706-2fbf-4ee8-80cf-93fb7cecf8c4.png)
![image](https://user-images.githubusercontent.com/3441348/181934910-8206299d-d76e-4806-97d6-209b31a7f059.png)
![image](https://user-images.githubusercontent.com/3441348/181934911-69518269-150c-47a0-be88-0bcd1de0e88d.png)

I've also attached a debug log from the current session.

[EDIT] Forgot to mention my specs:

i9-9900K@4,80GHz
32GB DDR5
GeForce RTX 2070 SUPER 6GB

Any help is greatly appreciated!

Sorry for opening an issue here but i didn't find any other way to contact you.

Regards
Alex

[x4-game-2022-07-30__12-45-41.log](https://github.com/DeadAirRT/deadairfactionmindatar/files/9227004/x4-game-2022-07-30__12-45-41.log)

**Comment by DeadAirRT** [comment]
I am so sorry that I didn't see this. I know it's obviously very late but some of my mods in the past were quite heavy on performance especially combined with the faction enhancers. Things have improved quite a bit since then but I hope you are doing well. There wasn't anything egregious in the debug log.
